apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JR2RNRkVDQVFBd0hqRU5NQXNHQTFVRUF3d0VkWE5sY2pFTk1Bc0dBMVVFQ2d3RVpXUnBkREFxTUFVR0F5dGwNCmNBTWhBTUwxZERURzE2UmQ3K2pORmhVQ05zMU94R1pTN0UvYXZ6ZW92T05oMXhCNm9BQXdCUVlESzJWd0EwRUENCnh1VFp6c05uMlM4ZXVuUlBOZUxoWElaOXVhRVlzQUNWR2ZOa29uSURHRW1oNWs5dWEzbndtU0V5b2Q5Q2JKN2QNClN0djVHNlN0dys4Sm1zbG1sZ1NmQXc9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tDQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 172800
  usages:
  - client auth